### ISSUE TITLE
Tray indicator persists even when the device has been unplugged or disconnected.

### ISSUE THREAD

**Issue by duymazino** [vchlum/wireless-hid#18]
Bug is still happening as of Gnome 43.2 with the lastest version of the extension. (I don't know how to check version but I'm sure it's the latest). Re-installing didn't help.

As title suggested. Can be removed by turning the extension on and off again.

Tray indicator functions normally when device is connected. However just refuses to go away afterward. Please fix.

**Comment by stuarthayhurst** [comment]
@vchlum I would look into this since I probably caused the issue in the first place with the new code (sorry), but I'm a bit swamped with coursework and exams until the summer. I'm happy to help out though, I just don't have time to reproduce this and troubleshoot it.

@duymazino As a workaround, have you tried changing the setting in the extension's preferences?

**Comment by vchlum** [comment]
fixed
